from pathlib import Path
import json


# ============================================================
# Configuration
# ============================================================

TRANSCRIPT_PATH = Path("transcript.json")


# ============================================================
# Transcript Loader
# ============================================================

class TranscriptLoader:
    """
    Loads the segment-level transcript generated by
    Whisper Large-v3-Turbo through Google Colab.

    Whisper inference is performed in Colab because GPU
    acceleration is required for efficient transcription.
    """

    def __init__(self, transcript_path=TRANSCRIPT_PATH):

        self.transcript_path = Path(transcript_path)

    def load(self):
        """
        Load transcript.json and return the transcript data.
        """

        if not self.transcript_path.exists():
            raise FileNotFoundError(
                f"Transcript file not found: "
                f"{self.transcript_path}"
            )

        with open(
            self.transcript_path,
            "r",
            encoding="utf-8"
        ) as f:

            data = json.load(f)

        return data

    def get_segments(self):
        """
        Return the segment-level transcript.
        """

        data = self.load()

        return data.get("segments", [])


# ============================================================
# Main
# ============================================================

if __name__ == "__main__":

    loader = TranscriptLoader()

    segments = loader.get_segments()

    print("\n========================================")
    print("TRANSCRIPT LOADED")
    print("========================================")

    print(f"Transcript : {TRANSCRIPT_PATH}")
    print(f"Segments   : {len(segments)}")