from pathlib import Path
import json


# ============================================================
# Configuration
# ============================================================

WORD_TRANSCRIPT_PATH = Path("word_transcribe.json")


# ============================================================
# Word Transcript Loader
# ============================================================

class WordTranscriptLoader:
    """
    Loads the word-level transcript generated by
    Whisper Large-v3-Turbo through Google Colab.

    The word-level transcript is generated only for the
    approximate dialogue range identified by BM25.
    """

    def __init__(
        self,
        word_transcript_path=WORD_TRANSCRIPT_PATH
    ):

        self.word_transcript_path = Path(
            word_transcript_path
        )

    def load(self):
        """
        Load word_transcribe.json.
        """

        if not self.word_transcript_path.exists():
            raise FileNotFoundError(
                f"Word transcript not found: "
                f"{self.word_transcript_path}"
            )

        with open(
            self.word_transcript_path,
            "r",
            encoding="utf-8"
        ) as f:

            data = json.load(f)

        return data

    def get_words(self):
        """
        Return the word-level transcript.
        """

        data = self.load()

        return data.get("words", [])


# ============================================================
# Main
# ============================================================

if __name__ == "__main__":

    loader = WordTranscriptLoader()

    words = loader.get_words()

    print("\n========================================")
    print("WORD TRANSCRIPT LOADED")
    print("========================================")

    print(
        f"Word transcript : "
        f"{WORD_TRANSCRIPT_PATH}"
    )

    print(f"Words           : {len(words)}")